pcre-7.2
bk: 47ff816dvNxEeU5rfP8-N6haqEyBEg

diff --git a/RunTest b/RunTest
--- a/RunTest
+++ b/RunTest
@@ -37,6 +37,7 @@ do6=no
 do7=no
 do8=no
 do9=no
+do10=no
 
 while [ $# -gt 0 ] ; do
   case $1 in
@@ -49,26 +50,12 @@ while [ $# -gt 0 ] ; do
     7) do7=yes;;
     8) do8=yes;;
     9) do9=yes;;
-    valgrind) valgrind="valgrind -q";;
+   10) do10=yes;;
+   valgrind) valgrind="valgrind -q";;
     *) echo "Unknown test number $1"; exit 1;;
   esac
   shift
 done
-
-if [ "$link_size" != "2" ] ; then
-  if [ $do2 = yes ] ; then
-    echo "Can't run test 2 with an internal link size other than 2"
-    exit 1
-  fi
-  if [ $do5 = yes ] ; then
-    echo "Can't run test 5 with an internal link size other than 2"
-    exit 1
-  fi
-  if [ $do6 = yes ] ; then
-    echo "Can't run test 6 with an internal link size other than 2"
-    exit 1
-  fi
-fi
 
 if [ $utf8 -eq 0 ] ; then
   if [ $do4 = yes ] ; then
@@ -79,16 +66,8 @@ if [ $utf8 -eq 0 ] ; then
     echo "Can't run test 5 because UTF-8 support is not configured"
     exit 1
   fi
-  if [ $do6 = yes ] ; then
-    echo "Can't run test 6 because UTF-8 support is not configured"
-    exit 1
-  fi
   if [ $do8 = yes ] ; then
     echo "Can't run test 8 because UTF-8 support is not configured"
-    exit 1
-  fi
-  if [ $do9 = yes ] ; then
-    echo "Can't run test 9 because UTF-8 support is not configured"
     exit 1
   fi
 fi
@@ -102,13 +81,24 @@ if [ $ucp -eq 0 ] ; then
     echo "Can't run test 9 because Unicode property support is not configured"
     exit 1
   fi
+  if [ $do10 = yes ] ; then
+    echo "Can't run test 10 because Unicode property support is not configured"
+    exit 1
+  fi
+fi
+
+if [ $link_size -ne 2 ] ; then
+  if [ $do10 = yes ] ; then
+    echo "Can't run test 10 because the link size ($link_size) is not 2"
+    exit 1
+  fi
 fi
 
 # If no specific tests were requested, select all that are relevant.
 
 if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no -a \
      $do5 = no -a $do6 = no -a $do7 = no -a $do8 = no -a \
-     $do9 = no ] ; then
+     $do9 = no -a $do10 = no ] ; then
   do1=yes
   do2=yes
   do3=yes
@@ -118,6 +108,7 @@ if [ $do1 = no -a $do2 = no -a $do3 = no -a $do4 = no -a \
   do7=yes
   if [ $utf8 -ne 0 ] ; then do8=yes; fi
   if [ $utf8 -ne 0 -a $ucp -ne 0 ] ; then do9=yes; fi
+  if [ $link_size -eq 2 -a $ucp -ne 0 ] ; then do10=yes; fi
 fi
 
 # Show which release
@@ -132,7 +123,7 @@ if [ $do1 = yes ] ; then
   echo "Test 1: main functionality (Perl compatible)"
   $valgrind ./pcretest -q $testdata/testinput1 testtry
   if [ $? = 0 ] ; then
-    $cf testtry $testdata/testoutput1
+    $cf $testdata/testoutput1 testtry
     if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
@@ -142,32 +133,44 @@ fi
 # PCRE tests that are not Perl-compatible - API & error tests, mostly
 
 if [ $do2 = yes ] ; then
-  if [ "$link_size" = "2" ] ; then
-    echo "Test 2: API and error handling (not Perl compatible)"
-    $valgrind ./pcretest -q $testdata/testinput2 testtry
-    if [ $? = 0 ] ; then
-      $cf testtry $testdata/testoutput2
-      if [ $? != 0 ] ; then exit 1; fi
-    else exit 1
-    fi
-    echo "OK"
-  else
-    echo Test 2 skipped for link size other than 2 \($link_size\)
-    echo " "
+  echo "Test 2: API and error handling (not Perl compatible)"
+  $valgrind ./pcretest -q $testdata/testinput2 testtry
+  if [ $? = 0 ] ; then
+    $cf $testdata/testoutput2 testtry
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
   fi
+  echo "OK"
 fi
 
-# Locale-specific tests, provided the "fr_FR" locale is available.
-# TODO: Try the locale name "french" instead - as used on Windows - but
-# this will mean modifying the input and output data.
+# Locale-specific tests, provided that either the "fr_FR" or the "french"
+# locale is available. The former is the Unix-like standard; the latter is
+# for Windows.
 
 if [ $do3 = yes ] ; then
   locale -a | grep '^fr_FR$' >/dev/null
   if [ $? -eq 0 ] ; then
-    echo "Test 3: locale-specific features (using 'fr_FR' locale)"
-    $valgrind ./pcretest -q $testdata/testinput3 testtry
+    locale=fr_FR
+    infile=$testdata/testinput3
+    outfile=$testdata/testoutput3
+  else
+    locale -a | grep '^french$' >/dev/null
+    if [ $? -eq 0 ] ; then
+      locale=french
+      sed 's/fr_FR/french/' $testdata/testinput3 >test3input
+      sed 's/fr_FR/french/' $testdata/testoutput3 >test3output
+      infile=test3input
+      outfile=test3output
+    else
+      locale=
+    fi
+  fi
+
+  if [ "$locale" != "" ] ; then
+    echo "Test 3: locale-specific features (using '$locale' locale)"
+    $valgrind ./pcretest -q $infile testtry
     if [ $? = 0 ] ; then
-      $cf testtry $testdata/testoutput3
+      $cf $outfile testtry
       if [ $? != 0 ] ; then
         echo " "
         echo "Locale test did not run entirely successfully."
@@ -179,8 +182,9 @@ if [ $do3 = yes ] ; then
     else exit 1
     fi
   else
-    echo "Cannot test locale-specific features - 'fr_FR' locale not found,"
-    echo "or the \"locale\" command is not available to check for it."
+    echo "Cannot test locale-specific features - neither the 'fr_FR' nor the"
+    echo "'french' locale exists, or the \"locale\" command is not available"
+    echo "to check for them."
     echo " "
   fi
 fi
@@ -191,7 +195,7 @@ if [ $do4 = yes ] ; then
   echo "Test 4: UTF-8 support (Perl compatible)"
   $valgrind ./pcretest -q $testdata/testinput4 testtry
   if [ $? = 0 ] ; then
-    $cf testtry $testdata/testoutput4
+    $cf $testdata/testoutput4 testtry
     if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
@@ -199,35 +203,25 @@ if [ $do4 = yes ] ; then
 fi
 
 if [ $do5 = yes ] ; then
-  if [ "$link_size" = "2" ] ; then
-    echo "Test 5: API and internals for UTF-8 support (not Perl compatible)"
-    $valgrind ./pcretest -q $testdata/testinput5 testtry
-    if [ $? = 0 ] ; then
-      $cf testtry $testdata/testoutput5
-      if [ $? != 0 ] ; then exit 1; fi
-    else exit 1
-    fi
-    echo "OK"
-  else
-    echo Test 5 skipped for link size other than 2 \($link_size\)
-    echo " "
+  echo "Test 5: API and internals for UTF-8 support (not Perl compatible)"
+  $valgrind ./pcretest -q $testdata/testinput5 testtry
+  if [ $? = 0 ] ; then
+    $cf $testdata/testoutput5 testtry
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
   fi
+  echo "OK"
 fi
 
 if [ $do6 = yes ] ; then
-  if [ "$link_size" = "2" ] ; then
-    echo "Test 6: Unicode property support"
-    $valgrind ./pcretest -q $testdata/testinput6 testtry
-    if [ $? = 0 ] ; then
-      $cf testtry $testdata/testoutput6
-      if [ $? != 0 ] ; then exit 1; fi
-    else exit 1
-    fi
-    echo "OK"
-  else
-    echo Test 6 skipped for link size other than 2 \($link_size\)
-    echo " "
+  echo "Test 6: Unicode property support"
+  $valgrind ./pcretest -q $testdata/testinput6 testtry
+  if [ $? = 0 ] ; then
+    $cf $testdata/testoutput6 testtry
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
   fi
+  echo "OK"
 fi
 
 # Tests for DFA matching support
@@ -236,7 +230,7 @@ if [ $do7 = yes ] ; then
   echo "Test 7: DFA matching"
   $valgrind ./pcretest -q -dfa $testdata/testinput7 testtry
   if [ $? = 0 ] ; then
-    $cf testtry $testdata/testoutput7
+    $cf $testdata/testoutput7 testtry
     if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
@@ -247,7 +241,7 @@ if [ $do8 = yes ] ; then
   echo "Test 8: DFA matching with UTF-8"
   $valgrind ./pcretest -q -dfa $testdata/testinput8 testtry
   if [ $? = 0 ] ; then
-    $cf testtry $testdata/testoutput8
+    $cf $testdata/testoutput8 testtry
     if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
@@ -258,7 +252,24 @@ if [ $do9 = yes ] ; then
   echo "Test 9: DFA matching with Unicode properties"
   $valgrind ./pcretest -q -dfa $testdata/testinput9 testtry
   if [ $? = 0 ] ; then
-    $cf testtry $testdata/testoutput9
+    $cf $testdata/testoutput9 testtry
+    if [ $? != 0 ] ; then exit 1; fi
+  else exit 1
+  fi
+  echo "OK"
+fi
+
+# Test of internal offsets and code sizes. This test is run only when there
+# is Unicode property support and the link size is 2. The actual tests are
+# mostly the same as in some of the above, but in this test we inspect some
+# offsets and sizes that require a known link size. This is a doublecheck for
+# the maintainer, just in case something changes unexpectely.
+
+if [ $do10 = yes ] ; then
+  echo "Test 10: Internal offsets and code size tests"
+  $valgrind ./pcretest -q $testdata/testinput10 testtry
+  if [ $? = 0 ] ; then
+    $cf $testdata/testoutput10 testtry
     if [ $? != 0 ] ; then exit 1; fi
   else exit 1
   fi
